### ISSUE TITLE
CAUAMDNLBADS - Measure network bandwidth

### ISSUE THREAD

**Issue by albinwwoxnerud** [IndaPlus22/alww-vprytz-project#8]
CAUAMDNLBADS (The Comprehensive and Ultra-Advanced Multi-Dimensional Network Latency and Bandwidth Assessment and Diagnosis System)

Measure network speed

**Comment by vilhelmprytz** [comment]
- Network speed should be measured relatively to other measurements of the same device. Different devices perform differently. Related to #12.
